version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/11434'"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s


volumes:
  ollama-data:
