services:
  ollama:
    image: ollama/ollama:latest
    volumes: ["ollama-data:/root/.ollama"]
    ports: ["11434:11434"]

  oneforall:
    build: .
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on: [ollama]
volumes:
  ollama-data:
