services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/11434'"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s

  oneforall:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    entrypoint: ["/bin/sh", "-c", "sleep infinity"]
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - CHROMA_PATH=/app/.chroma
    volumes:
      - ../:/app
    depends_on:
      ollama:
        condition: service_healthy

volumes:
  ollama-data:
